// Sentinel Log AI - gRPC Protocol Definition
// Defines the communication interface between the Go agent and Python ML engine.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/ml/v1/ml_service.proto

package mlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLService_Embed_FullMethodName         = "/sentinel.ml.v1.MLService/Embed"
	MLService_EmbedStream_FullMethodName   = "/sentinel.ml.v1.MLService/EmbedStream"
	MLService_Search_FullMethodName        = "/sentinel.ml.v1.MLService/Search"
	MLService_Cluster_FullMethodName       = "/sentinel.ml.v1.MLService/Cluster"
	MLService_DetectNovelty_FullMethodName = "/sentinel.ml.v1.MLService/DetectNovelty"
	MLService_Explain_FullMethodName       = "/sentinel.ml.v1.MLService/Explain"
	MLService_Health_FullMethodName        = "/sentinel.ml.v1.MLService/Health"
)

// MLServiceClient is the client API for MLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MLService provides AI/ML capabilities for log analysis.
// The Go agent calls this service to embed, cluster, and explain logs.
type MLServiceClient interface {
	// Embed converts log messages into vector embeddings.
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// EmbedStream provides streaming embedding for high-throughput ingestion.
	EmbedStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedRequest, EmbedResponse], error)
	// Search finds similar logs using vector similarity.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Cluster groups similar logs and returns cluster summaries.
	Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterResponse, error)
	// DetectNovelty checks if a log pattern is novel/unseen.
	DetectNovelty(ctx context.Context, in *NoveltyRequest, opts ...grpc.CallOption) (*NoveltyResponse, error)
	// Explain generates LLM explanation for a cluster.
	Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	// Health check for the ML service.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mLServiceClient{cc}
}

func (c *mLServiceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, MLService_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) EmbedStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedRequest, EmbedResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MLService_ServiceDesc.Streams[0], MLService_EmbedStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmbedRequest, EmbedResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLService_EmbedStreamClient = grpc.BidiStreamingClient[EmbedRequest, EmbedResponse]

func (c *mLServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MLService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterResponse)
	err := c.cc.Invoke(ctx, MLService_Cluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) DetectNovelty(ctx context.Context, in *NoveltyRequest, opts ...grpc.CallOption) (*NoveltyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoveltyResponse)
	err := c.cc.Invoke(ctx, MLService_DetectNovelty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, MLService_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MLService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLServiceServer is the server API for MLService service.
// All implementations must embed UnimplementedMLServiceServer
// for forward compatibility.
//
// MLService provides AI/ML capabilities for log analysis.
// The Go agent calls this service to embed, cluster, and explain logs.
type MLServiceServer interface {
	// Embed converts log messages into vector embeddings.
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// EmbedStream provides streaming embedding for high-throughput ingestion.
	EmbedStream(grpc.BidiStreamingServer[EmbedRequest, EmbedResponse]) error
	// Search finds similar logs using vector similarity.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Cluster groups similar logs and returns cluster summaries.
	Cluster(context.Context, *ClusterRequest) (*ClusterResponse, error)
	// DetectNovelty checks if a log pattern is novel/unseen.
	DetectNovelty(context.Context, *NoveltyRequest) (*NoveltyResponse, error)
	// Explain generates LLM explanation for a cluster.
	Explain(context.Context, *ExplainRequest) (*ExplainResponse, error)
	// Health check for the ML service.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMLServiceServer()
}

// UnimplementedMLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLServiceServer struct{}

func (UnimplementedMLServiceServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedMLServiceServer) EmbedStream(grpc.BidiStreamingServer[EmbedRequest, EmbedResponse]) error {
	return status.Error(codes.Unimplemented, "method EmbedStream not implemented")
}
func (UnimplementedMLServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMLServiceServer) Cluster(context.Context, *ClusterRequest) (*ClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cluster not implemented")
}
func (UnimplementedMLServiceServer) DetectNovelty(context.Context, *NoveltyRequest) (*NoveltyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectNovelty not implemented")
}
func (UnimplementedMLServiceServer) Explain(context.Context, *ExplainRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedMLServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMLServiceServer) mustEmbedUnimplementedMLServiceServer() {}
func (UnimplementedMLServiceServer) testEmbeddedByValue()                   {}

// UnsafeMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLServiceServer will
// result in compilation errors.
type UnsafeMLServiceServer interface {
	mustEmbedUnimplementedMLServiceServer()
}

func RegisterMLServiceServer(s grpc.ServiceRegistrar, srv MLServiceServer) {
	// If the following call panics, it indicates UnimplementedMLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLService_ServiceDesc, srv)
}

func _MLService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_EmbedStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MLServiceServer).EmbedStream(&grpc.GenericServerStream[EmbedRequest, EmbedResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLService_EmbedStreamServer = grpc.BidiStreamingServer[EmbedRequest, EmbedResponse]

func _MLService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_Cluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Cluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Cluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Cluster(ctx, req.(*ClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_DetectNovelty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoveltyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).DetectNovelty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_DetectNovelty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).DetectNovelty(ctx, req.(*NoveltyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Explain(ctx, req.(*ExplainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLService_ServiceDesc is the grpc.ServiceDesc for MLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.ml.v1.MLService",
	HandlerType: (*MLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _MLService_Embed_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MLService_Search_Handler,
		},
		{
			MethodName: "Cluster",
			Handler:    _MLService_Cluster_Handler,
		},
		{
			MethodName: "DetectNovelty",
			Handler:    _MLService_DetectNovelty_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _MLService_Explain_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MLService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EmbedStream",
			Handler:       _MLService_EmbedStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ml/v1/ml_service.proto",
}
