// Sentinel Log AI - gRPC Protocol Definition
// Defines the communication interface between the Go agent and Python ML engine.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/ml/v1/ml_service.proto

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogRecord represents a single log entry.
type LogRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this record (optional, agent-assigned)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Original log message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Normalized/masked message (for embedding)
	Normalized string `protobuf:"bytes,3,opt,name=normalized,proto3" json:"normalized,omitempty"`
	// Log level (INFO, WARN, ERROR, etc.)
	Level string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	// Source of the log (file path, journald unit, etc.)
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Timestamp of the log entry
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Additional attributes as JSON string
	AttrsJson     string `protobuf:"bytes,7,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetAttrsJson() string {
	if x != nil {
		return x.AttrsJson
	}
	return ""
}

// EmbedRequest contains logs to embed.
type EmbedRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Whether to use the cache
	UseCache      bool `protobuf:"varint,2,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedRequest) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *EmbedRequest) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

// EmbedResponse contains the embeddings.
type EmbedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embeddings as flattened float array (reshape to [n_records, embedding_dim])
	Embeddings []float32 `protobuf:"fixed32,1,rep,packed,name=embeddings,proto3" json:"embeddings,omitempty"`
	// Dimension of each embedding
	EmbeddingDim int32 `protobuf:"varint,2,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	// Number of cache hits
	CacheHits     int32 `protobuf:"varint,3,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedResponse) GetEmbeddings() []float32 {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbedResponse) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *EmbedResponse) GetCacheHits() int32 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

// SearchRequest for finding similar logs.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The log to find similar matches for
	Query *LogRecord `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Number of similar logs to return
	TopK int32 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Minimum similarity threshold (0.0 - 1.0)
	MinSimilarity float32 `protobuf:"fixed32,3,opt,name=min_similarity,json=minSimilarity,proto3" json:"min_similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() *LogRecord {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetMinSimilarity() float32 {
	if x != nil {
		return x.MinSimilarity
	}
	return 0
}

// SearchResult is a single similar log.
type SearchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching log record
	Record *LogRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// Similarity score (0.0 - 1.0, higher is more similar)
	Similarity float32 `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// Distance in embedding space
	Distance float32 `protobuf:"fixed32,3,opt,name=distance,proto3" json:"distance,omitempty"`
	// Cluster ID this log belongs to (if clustered)
	ClusterId     string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetRecord() *LogRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SearchResult) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *SearchResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResult) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// SearchResponse contains similar log matches.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// ClusterRequest for clustering logs.
type ClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logs to cluster (if empty, clusters all stored logs)
	Records []*LogRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Minimum cluster size
	MinClusterSize int32 `protobuf:"varint,2,opt,name=min_cluster_size,json=minClusterSize,proto3" json:"min_cluster_size,omitempty"`
	// Whether to persist cluster assignments
	Persist       bool `protobuf:"varint,3,opt,name=persist,proto3" json:"persist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRequest) Reset() {
	*x = ClusterRequest{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRequest) ProtoMessage() {}

func (x *ClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRequest.ProtoReflect.Descriptor instead.
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterRequest) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ClusterRequest) GetMinClusterSize() int32 {
	if x != nil {
		return x.MinClusterSize
	}
	return 0
}

func (x *ClusterRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

// ClusterSummary describes a log cluster.
type ClusterSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable cluster identifier
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Number of logs in this cluster
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Representative log message
	Representative string `protobuf:"bytes,3,opt,name=representative,proto3" json:"representative,omitempty"`
	// Top keywords/tokens in this cluster
	Keywords []string `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// Cohesion score (how tight the cluster is, 0.0 - 1.0)
	Cohesion float32 `protobuf:"fixed32,5,opt,name=cohesion,proto3" json:"cohesion,omitempty"`
	// Whether this is a new cluster (first seen this run)
	IsNew         bool `protobuf:"varint,6,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSummary) Reset() {
	*x = ClusterSummary{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSummary) ProtoMessage() {}

func (x *ClusterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSummary.ProtoReflect.Descriptor instead.
func (*ClusterSummary) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterSummary) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterSummary) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ClusterSummary) GetRepresentative() string {
	if x != nil {
		return x.Representative
	}
	return ""
}

func (x *ClusterSummary) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ClusterSummary) GetCohesion() float32 {
	if x != nil {
		return x.Cohesion
	}
	return 0
}

func (x *ClusterSummary) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

// ClusterResponse contains clustering results.
type ClusterResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Clusters []*ClusterSummary      `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	// Number of noise points (logs that didn't cluster)
	NoiseCount int32 `protobuf:"varint,2,opt,name=noise_count,json=noiseCount,proto3" json:"noise_count,omitempty"`
	// Total logs processed
	TotalProcessed int32 `protobuf:"varint,3,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterResponse) Reset() {
	*x = ClusterResponse{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResponse) ProtoMessage() {}

func (x *ClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResponse.ProtoReflect.Descriptor instead.
func (*ClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{8}
}

func (x *ClusterResponse) GetClusters() []*ClusterSummary {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClusterResponse) GetNoiseCount() int32 {
	if x != nil {
		return x.NoiseCount
	}
	return 0
}

func (x *ClusterResponse) GetTotalProcessed() int32 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

// NoveltyRequest for detecting novel patterns.
type NoveltyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The log to check for novelty
	Record *LogRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// Novelty threshold (above this = novel)
	Threshold     float32 `protobuf:"fixed32,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoveltyRequest) Reset() {
	*x = NoveltyRequest{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoveltyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoveltyRequest) ProtoMessage() {}

func (x *NoveltyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoveltyRequest.ProtoReflect.Descriptor instead.
func (*NoveltyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{9}
}

func (x *NoveltyRequest) GetRecord() *LogRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *NoveltyRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

// NoveltyResponse indicates if a log is novel.
type NoveltyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this log pattern is novel
	IsNovel bool `protobuf:"varint,1,opt,name=is_novel,json=isNovel,proto3" json:"is_novel,omitempty"`
	// Novelty score (0.0 = seen before, 1.0 = completely new)
	NoveltyScore float32 `protobuf:"fixed32,2,opt,name=novelty_score,json=noveltyScore,proto3" json:"novelty_score,omitempty"`
	// Closest cluster (if any)
	ClosestClusterId string `protobuf:"bytes,3,opt,name=closest_cluster_id,json=closestClusterId,proto3" json:"closest_cluster_id,omitempty"`
	// Distance to closest cluster
	DistanceToCluster float32 `protobuf:"fixed32,4,opt,name=distance_to_cluster,json=distanceToCluster,proto3" json:"distance_to_cluster,omitempty"`
	// Explanation of novelty assessment
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoveltyResponse) Reset() {
	*x = NoveltyResponse{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoveltyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoveltyResponse) ProtoMessage() {}

func (x *NoveltyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoveltyResponse.ProtoReflect.Descriptor instead.
func (*NoveltyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{10}
}

func (x *NoveltyResponse) GetIsNovel() bool {
	if x != nil {
		return x.IsNovel
	}
	return false
}

func (x *NoveltyResponse) GetNoveltyScore() float32 {
	if x != nil {
		return x.NoveltyScore
	}
	return 0
}

func (x *NoveltyResponse) GetClosestClusterId() string {
	if x != nil {
		return x.ClosestClusterId
	}
	return ""
}

func (x *NoveltyResponse) GetDistanceToCluster() float32 {
	if x != nil {
		return x.DistanceToCluster
	}
	return 0
}

func (x *NoveltyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ExplainRequest for generating LLM explanations.
type ExplainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster ID to explain
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// OR provide logs directly
	SampleLogs []*LogRecord `protobuf:"bytes,2,rep,name=sample_logs,json=sampleLogs,proto3" json:"sample_logs,omitempty"`
	// Context from previous explanations (for consistency)
	Context string `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	// Model to use (e.g., "llama3.2", "mistral")
	Model         string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{11}
}

func (x *ExplainRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ExplainRequest) GetSampleLogs() []*LogRecord {
	if x != nil {
		return x.SampleLogs
	}
	return nil
}

func (x *ExplainRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ExplainRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// ExplainResponse contains the LLM explanation.
type ExplainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Probable root cause
	RootCause string `protobuf:"bytes,1,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	// Suggested next steps
	NextSteps []string `protobuf:"bytes,2,rep,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	// Suggested remediation
	Remediation string `protobuf:"bytes,3,opt,name=remediation,proto3" json:"remediation,omitempty"`
	// Confidence level (LOW, MEDIUM, HIGH)
	Confidence string `protobuf:"bytes,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Numeric confidence score (0.0 - 1.0)
	ConfidenceScore float32 `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	// Why this confidence was assigned
	ConfidenceReasoning string `protobuf:"bytes,6,opt,name=confidence_reasoning,json=confidenceReasoning,proto3" json:"confidence_reasoning,omitempty"`
	// Raw LLM response (for debugging)
	RawResponse   string `protobuf:"bytes,7,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExplainResponse) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *ExplainResponse) GetNextSteps() []string {
	if x != nil {
		return x.NextSteps
	}
	return nil
}

func (x *ExplainResponse) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *ExplainResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *ExplainResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ExplainResponse) GetConfidenceReasoning() string {
	if x != nil {
		return x.ConfidenceReasoning
	}
	return ""
}

func (x *ExplainResponse) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

// HealthRequest for health checks.
type HealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include detailed component status
	Detailed      bool `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{13}
}

func (x *HealthRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

// ComponentHealth describes a component's health.
type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{14}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthResponse indicates service health.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Components    []*ComponentHealth     `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_v1_ml_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_v1_ml_service_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_proto_ml_v1_ml_service_proto protoreflect.FileDescriptor

const file_proto_ml_v1_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ml/v1/ml_service.proto\x12\x0esentinel.ml.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\tLogRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"normalized\x18\x03 \x01(\tR\n" +
	"normalized\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\a \x01(\tR\tattrsJson\"`\n" +
	"\fEmbedRequest\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.sentinel.ml.v1.LogRecordR\arecords\x12\x1b\n" +
	"\tuse_cache\x18\x02 \x01(\bR\buseCache\"w\n" +
	"\rEmbedResponse\x12\"\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\x02B\x02\x10\x01R\n" +
	"embeddings\x12#\n" +
	"\rembedding_dim\x18\x02 \x01(\x05R\fembeddingDim\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x03 \x01(\x05R\tcacheHits\"|\n" +
	"\rSearchRequest\x12/\n" +
	"\x05query\x18\x01 \x01(\v2\x19.sentinel.ml.v1.LogRecordR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12%\n" +
	"\x0emin_similarity\x18\x03 \x01(\x02R\rminSimilarity\"\x9c\x01\n" +
	"\fSearchResult\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.sentinel.ml.v1.LogRecordR\x06record\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x02R\n" +
	"similarity\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x02R\bdistance\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\"H\n" +
	"\x0eSearchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.sentinel.ml.v1.SearchResultR\aresults\"\x89\x01\n" +
	"\x0eClusterRequest\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.sentinel.ml.v1.LogRecordR\arecords\x12(\n" +
	"\x10min_cluster_size\x18\x02 \x01(\x05R\x0eminClusterSize\x12\x18\n" +
	"\apersist\x18\x03 \x01(\bR\apersist\"\xba\x01\n" +
	"\x0eClusterSummary\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12&\n" +
	"\x0erepresentative\x18\x03 \x01(\tR\x0erepresentative\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\x12\x1a\n" +
	"\bcohesion\x18\x05 \x01(\x02R\bcohesion\x12\x15\n" +
	"\x06is_new\x18\x06 \x01(\bR\x05isNew\"\x97\x01\n" +
	"\x0fClusterResponse\x12:\n" +
	"\bclusters\x18\x01 \x03(\v2\x1e.sentinel.ml.v1.ClusterSummaryR\bclusters\x12\x1f\n" +
	"\vnoise_count\x18\x02 \x01(\x05R\n" +
	"noiseCount\x12'\n" +
	"\x0ftotal_processed\x18\x03 \x01(\x05R\x0etotalProcessed\"a\n" +
	"\x0eNoveltyRequest\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.sentinel.ml.v1.LogRecordR\x06record\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x02R\tthreshold\"\xc7\x01\n" +
	"\x0fNoveltyResponse\x12\x19\n" +
	"\bis_novel\x18\x01 \x01(\bR\aisNovel\x12#\n" +
	"\rnovelty_score\x18\x02 \x01(\x02R\fnoveltyScore\x12,\n" +
	"\x12closest_cluster_id\x18\x03 \x01(\tR\x10closestClusterId\x12.\n" +
	"\x13distance_to_cluster\x18\x04 \x01(\x02R\x11distanceToCluster\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x9b\x01\n" +
	"\x0eExplainRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12:\n" +
	"\vsample_logs\x18\x02 \x03(\v2\x19.sentinel.ml.v1.LogRecordR\n" +
	"sampleLogs\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"\x92\x02\n" +
	"\x0fExplainResponse\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x01 \x01(\tR\trootCause\x12\x1d\n" +
	"\n" +
	"next_steps\x18\x02 \x03(\tR\tnextSteps\x12 \n" +
	"\vremediation\x18\x03 \x01(\tR\vremediation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\tR\n" +
	"confidence\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore\x121\n" +
	"\x14confidence_reasoning\x18\x06 \x01(\tR\x13confidenceReasoning\x12!\n" +
	"\fraw_response\x18\a \x01(\tR\vrawResponse\"+\n" +
	"\rHealthRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\"Y\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x85\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12?\n" +
	"\n" +
	"components\x18\x03 \x03(\v2\x1f.sentinel.ml.v1.ComponentHealthR\n" +
	"components2\x9d\x04\n" +
	"\tMLService\x12D\n" +
	"\x05Embed\x12\x1c.sentinel.ml.v1.EmbedRequest\x1a\x1d.sentinel.ml.v1.EmbedResponse\x12N\n" +
	"\vEmbedStream\x12\x1c.sentinel.ml.v1.EmbedRequest\x1a\x1d.sentinel.ml.v1.EmbedResponse(\x010\x01\x12G\n" +
	"\x06Search\x12\x1d.sentinel.ml.v1.SearchRequest\x1a\x1e.sentinel.ml.v1.SearchResponse\x12J\n" +
	"\aCluster\x12\x1e.sentinel.ml.v1.ClusterRequest\x1a\x1f.sentinel.ml.v1.ClusterResponse\x12P\n" +
	"\rDetectNovelty\x12\x1e.sentinel.ml.v1.NoveltyRequest\x1a\x1f.sentinel.ml.v1.NoveltyResponse\x12J\n" +
	"\aExplain\x12\x1e.sentinel.ml.v1.ExplainRequest\x1a\x1f.sentinel.ml.v1.ExplainResponse\x12G\n" +
	"\x06Health\x12\x1d.sentinel.ml.v1.HealthRequest\x1a\x1e.sentinel.ml.v1.HealthResponseB5Z3github.com/sentinel-log-ai/sentinel-log-ai/pkg/mlpbb\x06proto3"

var (
	file_proto_ml_v1_ml_service_proto_rawDescOnce sync.Once
	file_proto_ml_v1_ml_service_proto_rawDescData []byte
)

func file_proto_ml_v1_ml_service_proto_rawDescGZIP() []byte {
	file_proto_ml_v1_ml_service_proto_rawDescOnce.Do(func() {
		file_proto_ml_v1_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ml_v1_ml_service_proto_rawDesc), len(file_proto_ml_v1_ml_service_proto_rawDesc)))
	})
	return file_proto_ml_v1_ml_service_proto_rawDescData
}

var file_proto_ml_v1_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_ml_v1_ml_service_proto_goTypes = []any{
	(*LogRecord)(nil),             // 0: sentinel.ml.v1.LogRecord
	(*EmbedRequest)(nil),          // 1: sentinel.ml.v1.EmbedRequest
	(*EmbedResponse)(nil),         // 2: sentinel.ml.v1.EmbedResponse
	(*SearchRequest)(nil),         // 3: sentinel.ml.v1.SearchRequest
	(*SearchResult)(nil),          // 4: sentinel.ml.v1.SearchResult
	(*SearchResponse)(nil),        // 5: sentinel.ml.v1.SearchResponse
	(*ClusterRequest)(nil),        // 6: sentinel.ml.v1.ClusterRequest
	(*ClusterSummary)(nil),        // 7: sentinel.ml.v1.ClusterSummary
	(*ClusterResponse)(nil),       // 8: sentinel.ml.v1.ClusterResponse
	(*NoveltyRequest)(nil),        // 9: sentinel.ml.v1.NoveltyRequest
	(*NoveltyResponse)(nil),       // 10: sentinel.ml.v1.NoveltyResponse
	(*ExplainRequest)(nil),        // 11: sentinel.ml.v1.ExplainRequest
	(*ExplainResponse)(nil),       // 12: sentinel.ml.v1.ExplainResponse
	(*HealthRequest)(nil),         // 13: sentinel.ml.v1.HealthRequest
	(*ComponentHealth)(nil),       // 14: sentinel.ml.v1.ComponentHealth
	(*HealthResponse)(nil),        // 15: sentinel.ml.v1.HealthResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_proto_ml_v1_ml_service_proto_depIdxs = []int32{
	16, // 0: sentinel.ml.v1.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: sentinel.ml.v1.EmbedRequest.records:type_name -> sentinel.ml.v1.LogRecord
	0,  // 2: sentinel.ml.v1.SearchRequest.query:type_name -> sentinel.ml.v1.LogRecord
	0,  // 3: sentinel.ml.v1.SearchResult.record:type_name -> sentinel.ml.v1.LogRecord
	4,  // 4: sentinel.ml.v1.SearchResponse.results:type_name -> sentinel.ml.v1.SearchResult
	0,  // 5: sentinel.ml.v1.ClusterRequest.records:type_name -> sentinel.ml.v1.LogRecord
	7,  // 6: sentinel.ml.v1.ClusterResponse.clusters:type_name -> sentinel.ml.v1.ClusterSummary
	0,  // 7: sentinel.ml.v1.NoveltyRequest.record:type_name -> sentinel.ml.v1.LogRecord
	0,  // 8: sentinel.ml.v1.ExplainRequest.sample_logs:type_name -> sentinel.ml.v1.LogRecord
	14, // 9: sentinel.ml.v1.HealthResponse.components:type_name -> sentinel.ml.v1.ComponentHealth
	1,  // 10: sentinel.ml.v1.MLService.Embed:input_type -> sentinel.ml.v1.EmbedRequest
	1,  // 11: sentinel.ml.v1.MLService.EmbedStream:input_type -> sentinel.ml.v1.EmbedRequest
	3,  // 12: sentinel.ml.v1.MLService.Search:input_type -> sentinel.ml.v1.SearchRequest
	6,  // 13: sentinel.ml.v1.MLService.Cluster:input_type -> sentinel.ml.v1.ClusterRequest
	9,  // 14: sentinel.ml.v1.MLService.DetectNovelty:input_type -> sentinel.ml.v1.NoveltyRequest
	11, // 15: sentinel.ml.v1.MLService.Explain:input_type -> sentinel.ml.v1.ExplainRequest
	13, // 16: sentinel.ml.v1.MLService.Health:input_type -> sentinel.ml.v1.HealthRequest
	2,  // 17: sentinel.ml.v1.MLService.Embed:output_type -> sentinel.ml.v1.EmbedResponse
	2,  // 18: sentinel.ml.v1.MLService.EmbedStream:output_type -> sentinel.ml.v1.EmbedResponse
	5,  // 19: sentinel.ml.v1.MLService.Search:output_type -> sentinel.ml.v1.SearchResponse
	8,  // 20: sentinel.ml.v1.MLService.Cluster:output_type -> sentinel.ml.v1.ClusterResponse
	10, // 21: sentinel.ml.v1.MLService.DetectNovelty:output_type -> sentinel.ml.v1.NoveltyResponse
	12, // 22: sentinel.ml.v1.MLService.Explain:output_type -> sentinel.ml.v1.ExplainResponse
	15, // 23: sentinel.ml.v1.MLService.Health:output_type -> sentinel.ml.v1.HealthResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ml_v1_ml_service_proto_init() }
func file_proto_ml_v1_ml_service_proto_init() {
	if File_proto_ml_v1_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ml_v1_ml_service_proto_rawDesc), len(file_proto_ml_v1_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ml_v1_ml_service_proto_goTypes,
		DependencyIndexes: file_proto_ml_v1_ml_service_proto_depIdxs,
		MessageInfos:      file_proto_ml_v1_ml_service_proto_msgTypes,
	}.Build()
	File_proto_ml_v1_ml_service_proto = out.File
	file_proto_ml_v1_ml_service_proto_goTypes = nil
	file_proto_ml_v1_ml_service_proto_depIdxs = nil
}
